export const SPEC_KEY = 'SPEC';
export const LIMIT = 10;
export const FIRST_PAGE = 1;
export const DEFAULT_PERIOD = 3600000;
export const ENVS_ALLOW_DOCS = ['local', 'development'];

export const CACHE_KEYS = {
  ACCESS_TOKEN_BACKLIST: 'ACCESS_TOKEN_BACKLIST',
  BO_TYPES_LIST: 'BO_TYPES_LIST',
  BO_TYPE_NAME: 'BO_TYPE_NAME',
  BO_STATE_NAME: 'BO_STATE_NAME',
  BO_REGION_NAME: 'BO_REGION_NAME',
  BO_REGIONS_LIST: 'BO_REGIONS_LIST',
  BO_SOVEREIGNTIES_LIST: 'BO_SOVEREIGNTIES_LIST',
  BO_SOVEREIGNTY_NAME: 'BO_SOVEREIGNTY_NAME',
  BO_ALIASES_LIST: 'BO_ALIASES_LIST',
  BO_INTERNET_CCTLD_LIST: 'BO_INTERNET_CCTLD_LIST',
  BO_COUNTRY_SEASONS: 'BO_COUNTRY_SEASONS',
};

export const REGEX_SPLIT = /\/|,|-| or /i;

export const URL_PATTERN = /^(https?|ftp):\/\/[^\s/$.?#].[^\s]*$/i;
